apiVersion: skagents/v1
kind: Chat
description: >
  A local assistant that can suggest local activities or places to visit.
service_name: LocalAgent
version: 0.1
input_type: BaseMultiModalInput
spec:
  agent:
    name: default
    role: Default Agent
    model: gpt-4o-mini
    system_prompt: >
      You are a helpful assistant that can suggest authentic and interesting
      local activities or places to visit for a user and can utilize any context
      information provided.