[project]
name = "sk-agents"
version = "0.1.9"
description = "Teal Agents - Core Agent Framework"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "semantic-kernel==1.22.1",
    "pyyaml",
    "pydantic",
    "pydantic-yaml",
    "fastapi [standard]",
    "python-dotenv",
    "anthropic",
    "boto3",
    "PyGithub",
    "opentelemetry-exporter-otlp-proto-grpc",
    "ska-utils",
    "black",
    "lock",
]

[tool.uv.sources]
ska-utils = { path = "../../shared/ska_utils" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
