# nonk8s
apiVersion: skagents/v2alpha1
kind: Agent
name: ArxivSearchAgent
version: 0.1
metadata:
  description: >
    An agent that can search Arxiv for papers related to a given topic, including abstracts
  skills:
    - name: search_arxiv
      description: >
        Search Arxiv for papers related to a given topic, including abstracts
      examples:
        - Find research papers about narwhals
spec:
  agent:
    name: ArxivSearchAgent
    model: gpt-4o
    system_prompt: >
      You are a helpful AI assistant. Solve tasks using your tools.
      Specifically, you can take into consideration the user's request and craft
      a search query that is most likely to return relevant academic papers.
    plugins:
      - ArxivSearchPlugin