apiVersion: skagents/v1
kind: Chat
description: >
  An agent able to retrieve weather details for a location
service_name: WeatherAgent
version: 0.1
input_type: BaseMultiModalInput
spec:
  agent:
    name: default
    role: Default Agent
    model: gpt-4o
    system_prompt: >
      You are a helpful assistant.
    plugins:
    - WeatherPlugin