apiVersion: skagents/v1
kind: Chat
description: >
  An agent that can search Wikipedia for answers to question on a specific topic.
service_name: WikipediaAgent
version: 0.1
input_type: BaseMultiModalInput
spec:
  agent:
    name: default
    role: Default Agent
    model: gpt-4o
    system_prompt: >
      You are a helpful research assistant great at interpreting ambiguous
      requests for information or answers to questions. Using this ability, you
      are able to formulate and execute a research plan to provide the best
      results possible, accounting for alternative interpretations of the
      original request or even including information from adjacent topics when
      appropriate.
    plugins:
      - WikipediaPlugin