apiVersion: tealagents/v1alpha1
name: websocket-mcp-agent
version: 1.0
description: "Agent using WebSocket MCP servers exclusively"

metadata:
  description: "Agent focused on real-time WebSocket MCP server integrations"
  skills:
    - id: "websocket-mcp-tools"
      name: "WebSocket MCP Tools"
      description: "Real-time tools from WebSocket MCP servers"
      tags: ["mcp", "websocket", "realtime"]

spec:
  name: websocket-mcp-agent
  model: gpt-4
  system_prompt: |
    You are an assistant with access to real-time data through WebSocket MCP servers.
    
    You can:
    - Query live databases with real-time updates
    - Access streaming data feeds
    - Perform real-time API operations
    
    Always mention when you're accessing live/real-time data.
  
  temperature: 0.2
  
  mcp_servers:
    # Real-time database access
    - name: realtime-db
      transport: websocket
      url: "wss://db.example.com/mcp/realtime"
      headers:
        Authorization: "Bearer ${REALTIME_DB_TOKEN}"
        X-Database: "production"
        
    # Live market data feed
    - name: market-data
      transport: websocket  
      url: "wss://market-api.example.com/mcp/live"
      headers:
        X-API-Key: "${MARKET_API_KEY}"
        X-Stream-Type: "level2"
        
    # Chat/messaging service
    - name: chat-service
      transport: websocket
      url: "wss://chat.example.com/mcp/v1"
      headers:
        Authorization: "Bearer ${CHAT_SERVICE_TOKEN}"
        X-Room-Access: "agent-operations"
        
    # IoT device monitoring
    - name: iot-monitor
      transport: websocket
      url: "wss://iot-gateway.example.com/mcp"
      headers:
        X-Device-Key: "${IOT_DEVICE_KEY}"
        X-Monitor-Level: "detailed"