services:
  redis:
    image: "redis:6"
    ports:
      - "6379:6379"
  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - "18888:18888"
      - "4317:18889"
  placement:
    image: "daprio/dapr:1.14.4"
    command: ["./placement",
              "--log-level", "debug",
              "--port", "50005"]
    ports:
      - "50005:50005"
      - "58080:8080"
      - "59090:9090"
  scheduler:
    image: "daprio/dapr:1.14.4"
    command: ["./scheduler",
              "--port", "50006"]
    ports:
      - "50006:50006"
      - "52379:2379"
      - "58081:8080"
      - "59091:9090"
    volumes:
      - type: tmpfs
        target: /data
        tmpfs:
          size: 1000m
  dapr-sidecar:
    image: "daprio/daprd:1.14.4"
    command: ["./daprd",
              "--app-id", "workflow-orchestrator",
              "--placement-host-address", "placement:50005",
              "--scheduler-host-address", "scheduler:50006",
              "--dapr-http-port", "3500",
              "--dapr-grpc-port", "50001",
              "--resources-path", "/components",
              "--log-level", "debug",
              "--app-channel-address", "host.docker.internal"]
    depends_on:
      redis:
        condition: service_started
      placement:
        condition: service_started
      scheduler:
        condition: service_started
    volumes:
      - ./components:/components
    ports:
      - "3500:3500"
      - "50001:50001"