#nonk8s
apiVersion: skagents/v1
kind: PlanningOrchestrator
description: >
  A research assistant with access to Wikipedia and Arxiv
service_name: AltCollabOrchestrator
version: 0.1
spec:
  planning_agent: PlanningAgent:0.1
  agents:
    - WikipediaAgent:0.1
    - ArxivSearchAgent:0.1
    - AssistantAgent:0.1
