apiVersion: skagents/v1
kind: PlanningOrchestrator
description: >
  Group Orchestrator for demo
service_name: CollaborationOrchestrator
version: 0.1
spec:
  planning_agent: PlanningAgent:0.1
  agents:
    - WikipediaAgent:0.1
    - ArxivSearchAgent:0.1
    - AssistantAgent:0.1
