name: Build and Push teal-agents

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install hatch 
        run: uv tool install hatch
      
      - name: Extract version with hatch
        id: extract_version
        run: |
          cd src/sk-agents
          uv run hatch version
          VERSION=$( uv run hatch version )
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          cd ...

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/teal-agents/teal-agents:${{ steps.extract_version.outputs.VERSION }} -f teal-agents.Dockerfile .
          docker tag ghcr.io/teal-agents/teal-agents:${{ steps.extract_version.outputs.VERSION }} ghcr.io/teal-agents/teal-agents:latest

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/teal-agents/teal-agents:${{ steps.extract_version.outputs.VERSION }}
          docker push ghcr.io/teal-agents/teal-agents:latest