name: Build and push teal-utils

on:
  push:
    branches:
      - main
    paths:
      - 'shared/ska_utils/**'
      - .github/workflows/build-and-push-ska-utils.yml
  pull_request:
    # All PRs, including stacked PRs

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./shared/ska_utils
        run: make sync
      - name: Run lint
        working-directory: ./shared/ska_utils
        run: make lint

  typecheck:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./shared/ska_utils
        run: make sync
      - name: Run typecheck
        working-directory: ./shared/ska_utils
        run: make mypy

  tests:
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./shared/ska_utils
        run: make sync
      - name: Run tests with coverage
        working-directory: ./shared/ska_utils
        run: make coverage

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: tests
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./src/sk-agents
        run: make sync
      - name: bump version with hatch
        id: bump_version
        working-directory: ./src/orchestrators/assistant-orchestrator/services
        run: |
          git checkout ${{ github.ref_name }}
          uv run hatch version dev
          git config --global user.name "Teal Agents Bot"
          git config --global user.email " "
          git commit -am "bump dev version [skip ci]"
          git push --set-upstream origin ${{ github.ref_name }}
