name: Build and push teal-utils

on:
  push:
    branches:
      - main
  pull_request:
    # All PRs, including stacked PRs

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./shared/ska_utils
        run: make sync
      - name: Run lint
        working-directory: ./shared/ska_utils
        run: make lint

  typecheck:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./shared/ska_utils
        run: make sync
      - name: Run typecheck
        working-directory: ./shared/ska_utils
        run: make mypy

  tests:
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./shared/ska_utils
        run: make sync
      - name: Run tests with coverage
        working-directory: ./shared/ska_utils
        run: make coverage
