name: Build and push teal-utils

on:
  push:
    branches:
      - main
  pull_request:
    # All PRs, including stacked PRs

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./shared/ska_utils
        run: make sync
      - name: Run lint
        working-directory: ./shared/ska_utils
        run: make lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./shared/ska_utils
        run: make sync
      - name: Run typecheck
        working-directory: ./shared/ska_utils
        run: make mypy

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./shared/ska_utils
        run: make sync
      - name: Run tests with coverage
        working-directory: ./shared/ska_utils
        run: make coverage

  publish:
    environment:
      name: pypi
      url: https://pypi.org/p/teal-agent-utils
    permissions:
      id-token: write # Important for trusted publishing to PyPI
    runs-on: ubuntu-latest
    needs: package
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./shared/ska_utils
        run: uv sync
      - name: Build package
        working-directory: ./shared/ska_utils
        run: uv build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          packages-dir: ./shared/ska_utils/dist/
