name: Deploy docs

on:
  push:
    branches:
      - "feature/mkdocs"
  workflow_run:
    workflows: ["check"]
    types:
      - completed

permissions:
  contents: write # This allows pushing to gh-pages

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        working-directory: ./src/sk-agents
        run: make sync
      - name: Deploy docs
        working-directory: ./src/sk-agents/docs
        run: make deploy-docs
